services:
  mqtt-broker:
    image: eclipse-mosquitto
    restart: always
    ports:
      - 1883:1883
    volumes:
      - ./mqtt-broker/mosquitto.conf:/mosquitto/config/mosquitto.conf
  central-de-controle:
    build:
      context: .
      dockerfile: ./central-de-controle/Dockerfile
    restart: always
